import 'dart:io';

void main() {
  print("bienvenido");
   print("usuario ingrese su primer nombre");
  String? primerNombre = stdin.readLineSync();
  print("usuario ingrese su su segundo nombre");
  String? segundoNombre = stdin.readLineSync();
  print("usuario ingrese su primer apellido");
  String? primerApellido = stdin.readLineSync();
    print("usuario ingrese su segundo apellido");
  String? segundoApellido = stdin.readLineSync();
  }